"""
Chat API Schemas.
Defines models for validating requests and formatting responses.
"""

from typing import Optional
from pydantic import BaseModel, Field, field_validator

class ChatRequest(BaseModel):
    message: str = Field(..., description="The user message to send to the assistant.")
    session_id: Optional[str] = Field(None, description="The session identifier for tracking conversation context.")

    @field_validator("message")
    @classmethod
    def validate_message(cls, v: str) -> str:
        """
        Validates that the message is not empty or whitespace only.
        """
        if not v or not v.strip():
            raise ValueError("Message cannot be empty or whitespace only.")
        return v

class ChatResponse(BaseModel):
    response: str = Field(..., description="The reply generated by the co-founder assistant.")
    estimated_tokens: Optional[int] = Field(None, description="Estimated total tokens currently stored in active session memory.")

class ResetRequest(BaseModel):
    session_id: str = Field(..., description="The session identifier to clear.")

class ResetResponse(BaseModel):
    success: bool = Field(..., description="Indicates whether the reset operation succeeded.")
    message: str = Field(..., description="Detailed message outlining operation results.")

