"""
Chat API Schemas.
Defines models for validates requests and formatting responses.
"""

from pydantic import BaseModel, Field, field_validator

class ChatRequest(BaseModel):
    message: str = Field(..., description="The user message to send to Gemini.")

    @field_validator("message")
    @classmethod
    def validate_message(cls, v: str) -> str:
        """
        Validates that the message is not empty or whitespace only.
        """
        if not v or not v.strip():
            raise ValueError("Message cannot be empty or whitespace only.")
        return v

class ChatResponse(BaseModel):
    response: str = Field(..., description="The reply generated by Gemini.")
